name: Build extension

on:
#  release:
#    types: [published]
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.git/**'
      - '.github/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - uses: vimtor/action-zip@v1
#        with:
#          files: manifest.json favicon.svg credits.html background-coub-pl.js style/ js/ ico/ _locales/
#          recursive: false
#          dest: Polish-Coub.zip
      - name: Upload zip version
        uses: actions/upload-artifact@v3
        with:
          name: Polish-Coub
          path: ${{ github.workspace }}
